- name: update apt
  apt: >
    update_cache=yes
    cache_valid_time=3600
  when: ansible_os_family == "Debian"

- name: install deps (Ubuntu)
  apt: >
    pkg=dnsmasq
    state=installed
  when: ansible_os_family == "Debian"

- name: install deps (RHEL)
  yum: >
    name=dnsmasq
    state=installed
  when: ansible_os_family == "RedHat"

- name: ensure configure directory
  file: dest=/etc/dnsmasq.d state=directory

- name: ensure dnsmasq configuration
  lineinfile: dest="/etc/dnsmasq.conf"
              regexp="^#conf-dir=/etc/dnsmasq.conf"
              line="conf-dir=/etc/dnsmasq.d"
              state=present

- name: ensure configure directory
  file: dest=/etc/resolvconf/resolv.conf.d state=directory

- name: add local dns lookup
  lineinfile: line="nameserver 127.0.0.1" insertbefore=BOF state=present dest="/etc/resolvconf/resolv.conf.d/consul" create=yes

- name: configure dnsmasq to listen on loopback interface only
  lineinfile:
    dest: /etc/dnsmasq.conf
    regexp: "^#interface="
    line: "interface=lo"

- name: configure dnsmasq to disable DHCP and TFTP
  lineinfile:
    dest: /etc/dnsmasq.conf
    regexp: "^#no-dhcp-interface="
    line: "no-dhcp-interface=lo"

- name: configure dnsmasq to delegate all Consul DNS requests to the Consul DNS port
  copy: >
    content='server=/{{ consul_domain }}/{{ consul_client_address }}#{{ consul_port_dns }}'
    dest=/etc/dnsmasq.d/10-consul
  notify:
    - restart dnsmasq
- pause: seconds=15
